const bcrypt = require("bcryptjs");

async function generateMerchants() {
  const password = "StrongP@ss123";
  const hashedPassword = await bcrypt.hash(password, 10);

  const merchantData = [
    {
      fullName: "أحمد محمد السيد",
      companyName: "شركة النور للتجارة",
      phone: "01012345678",
      address: "شارع الجمهورية، القاهرة",
      governorate: "القاهرة",
      city: "مدينة نصر",
    },
    {
      fullName: "محمد أحمد عبدالله",
      companyName: "مؤسسة الأمل التجارية",
      phone: "01123456789",
      address: "شارع الهرم، الجيزة",
      governorate: "الجيزة",
      city: "الهرم",
    },
    {
      fullName: "خالد حسن علي",
      companyName: "شركة الفجر للاستيراد",
      phone: "01234567890",
      address: "كورنيش النيل، الإسكندرية",
      governorate: "الإسكندرية",
      city: "سموحة",
    },
    {
      fullName: "عمر يوسف إبراهيم",
      companyName: "مجموعة النجاح التجارية",
      phone: "01098765432",
      address: "شارع المعز، القاهرة",
      governorate: "القاهرة",
      city: "الأزهر",
    },
    {
      fullName: "ياسر محمود حسن",
      companyName: "شركة الرخاء للتوزيع",
      phone: "01187654321",
      address: "ميدان التحرير، القاهرة",
      governorate: "القاهرة",
      city: "وسط البلد",
    },
    {
      fullName: "طارق سعيد أحمد",
      companyName: "مؤسسة الازدهار",
      phone: "01276543210",
      address: "شارع فيصل، الجيزة",
      governorate: "الجيزة",
      city: "فيصل",
    },
    {
      fullName: "وليد عادل محمد",
      companyName: "شركة البركة التجارية",
      phone: "01065432109",
      address: "شارع الجيش، السويس",
      governorate: "السويس",
      city: "السويس",
    },
    {
      fullName: "كريم صلاح الدين",
      companyName: "مجموعة الشروق",
      phone: "01154321098",
      address: "شارع الثورة، بورسعيد",
      governorate: "بورسعيد",
      city: "بورسعيد",
    },
    {
      fullName: "مصطفى جمال عبدالناصر",
      companyName: "شركة الأفق للتجارة",
      phone: "01243210987",
      address: "شارع سعد زغلول، الإسماعيلية",
      governorate: "الإسماعيلية",
      city: "الإسماعيلية",
    },
    {
      fullName: "حسام الدين فاروق",
      companyName: "مؤسسة التقدم",
      phone: "01032109876",
      address: "شارع الجلاء، طنطا",
      governorate: "الغربية",
      city: "طنطا",
    },
    {
      fullName: "إسلام رمضان محمد",
      companyName: "شركة الوفاء التجارية",
      phone: "01121098765",
      address: "شارع الجمهورية، المنصورة",
      governorate: "الدقهلية",
      city: "المنصورة",
    },
    {
      fullName: "عبدالرحمن خالد",
      companyName: "مجموعة الإخلاص",
      phone: "01210987654",
      address: "شارع البحر، دمياط",
      governorate: "دمياط",
      city: "دمياط",
    },
    {
      fullName: "سامح عبدالعزيز",
      companyName: "شركة الثقة للاستيراد",
      phone: "01009876543",
      address: "شارع الحرية، الزقازيق",
      governorate: "الشرقية",
      city: "الزقازيق",
    },
    {
      fullName: "أيمن طه حسين",
      companyName: "مؤسسة الأمانة",
      phone: "01198765432",
      address: "شارع الجيش، بنها",
      governorate: "القليوبية",
      city: "بنها",
    },
    {
      fullName: "هشام نبيل فتحي",
      companyName: "شركة الصدق التجارية",
      phone: "01287654321",
      address: "شارع النصر، شبين الكوم",
      governorate: "المنوفية",
      city: "شبين الكوم",
    },
    {
      fullName: "رامي وائل سمير",
      companyName: "مجموعة الإنجاز",
      phone: "01076543210",
      address: "شارع المحطة، كفر الشيخ",
      governorate: "كفر الشيخ",
      city: "كفر الشيخ",
    },
    {
      fullName: "شريف ماجد عصام",
      companyName: "شركة النهضة",
      phone: "01165432109",
      address: "شارع الجمهورية، دمنهور",
      governorate: "البحيرة",
      city: "دمنهور",
    },
    {
      fullName: "باسم عماد الدين",
      companyName: "مؤسسة الريادة",
      phone: "01254321098",
      address: "شارع سعد زغلول، أسيوط",
      governorate: "أسيوط",
      city: "أسيوط",
    },
    {
      fullName: "معتز هاني محمود",
      companyName: "شركة التميز التجارية",
      phone: "01043210987",
      address: "شارع الثورة، سوهاج",
      governorate: "سوهاج",
      city: "سوهاج",
    },
    {
      fullName: "تامر شادي أحمد",
      companyName: "مجموعة الإبداع",
      phone: "01132109876",
      address: "شارع الجلاء، قنا",
      governorate: "قنا",
      city: "قنا",
    },
    {
      fullName: "عصام حازم علي",
      companyName: "شركة الابتكار",
      phone: "01221098765",
      address: "شارع النيل، الأقصر",
      governorate: "الأقصر",
      city: "الأقصر",
    },
    {
      fullName: "فادي كمال حسن",
      companyName: "مؤسسة التطوير",
      phone: "01010987654",
      address: "شارع البحر، أسوان",
      governorate: "أسوان",
      city: "أسوان",
    },
    {
      fullName: "نادر بسام محمد",
      companyName: "شركة الإتقان",
      phone: "01109876543",
      address: "شارع الجمهورية، الفيوم",
      governorate: "الفيوم",
      city: "الفيوم",
    },
    {
      fullName: "مروان علاء الدين",
      companyName: "مجموعة الجودة",
      phone: "01298765432",
      address: "شارع الحرية، بني سويف",
      governorate: "بني سويف",
      city: "بني سويف",
    },
    {
      fullName: "جمال رأفت سعيد",
      companyName: "شركة الكفاءة",
      phone: "01087654321",
      address: "شارع المحطة، المنيا",
      governorate: "المنيا",
      city: "المنيا",
    },
    {
      fullName: "سيد منير عبدالله",
      companyName: "مؤسسة الخبرة",
      phone: "01176543210",
      address: "شارع الجيش، مرسى مطروح",
      governorate: "مطروح",
      city: "مرسى مطروح",
    },
    {
      fullName: "حمدي صابر محمود",
      companyName: "شركة الاحتراف",
      phone: "01265432109",
      address: "شارع الثورة، العريش",
      governorate: "شمال سيناء",
      city: "العريش",
    },
    {
      fullName: "ماهر ناصر حسن",
      companyName: "مجموعة التفوق",
      phone: "01054321098",
      address: "شارع السلام، شرم الشيخ",
      governorate: "جنوب سيناء",
      city: "شرم الشيخ",
    },
    {
      fullName: "ياسين فؤاد علي",
      companyName: "شركة الامتياز",
      phone: "01143210987",
      address: "شارع الجمهورية، الغردقة",
      governorate: "البحر الأحمر",
      city: "الغردقة",
    },
    {
      fullName: "زياد منصور أحمد",
      companyName: "مؤسسة الرقي",
      phone: "01232109876",
      address: "شارع النصر، الوادي الجديد",
      governorate: "الوادي الجديد",
      city: "الخارجة",
    },
    {
      fullName: "عادل رشدي محمد",
      companyName: "شركة السمو التجارية",
      phone: "01021098765",
      address: "شارع الهرم، 6 أكتوبر",
      governorate: "الجيزة",
      city: "6 أكتوبر",
    },
    {
      fullName: "إيهاب سامي حسن",
      companyName: "مجموعة الرفعة",
      phone: "01110987654",
      address: "شارع التسعين، التجمع الخامس",
      governorate: "القاهرة",
      city: "التجمع الخامس",
    },
    {
      fullName: "مدحت عاطف علي",
      companyName: "شركة العلو",
      phone: "01209876543",
      address: "شارع الجامعة، الشيخ زايد",
      governorate: "الجيزة",
      city: "الشيخ زايد",
    },
    {
      fullName: "فتحي جابر محمود",
      companyName: "مؤسسة الشموخ",
      phone: "01098765432",
      address: "شارع مصر الجديدة، مصر الجديدة",
      governorate: "القاهرة",
      city: "مصر الجديدة",
    },
    {
      fullName: "سمير لطفي سعيد",
      companyName: "شركة العزة التجارية",
      phone: "01187654321",
      address: "شارع الهرم، المعادي",
      governorate: "القاهرة",
      city: "المعادي",
    },
    {
      fullName: "نبيل ثروت أحمد",
      companyName: "مجموعة الفخر",
      phone: "01276543210",
      address: "شارع الجامعة، حلوان",
      governorate: "القاهرة",
      city: "حلوان",
    },
    {
      fullName: "رفعت جلال محمد",
      companyName: "شركة المجد",
      phone: "01065432109",
      address: "شارع البحر، شبرا الخيمة",
      governorate: "القليوبية",
      city: "شبرا الخيمة",
    },
    {
      fullName: "صلاح زكي حسن",
      companyName: "مؤسسة الكرامة",
      phone: "01154321098",
      address: "شارع الجيش، القناطر الخيرية",
      governorate: "القليوبية",
      city: "القناطر الخيرية",
    },
    {
      fullName: "عزت حلمي علي",
      companyName: "شركة الشرف",
      phone: "01243210987",
      address: "شارع الثورة، العبور",
      governorate: "القليوبية",
      city: "العبور",
    },
    {
      fullName: "فاروق سليم محمود",
      companyName: "مجموعة النبل",
      phone: "01032109876",
      address: "شارع الجمهورية، مدينتي",
      governorate: "القاهرة",
      city: "مدينتي",
    },
    {
      fullName: "حسين عبدالحميد أحمد",
      companyName: "شركة الوقار",
      phone: "01121098765",
      address: "شارع النصر، الرحاب",
      governorate: "القاهرة",
      city: "الرحاب",
    },
    {
      fullName: "كمال عبدالفتاح محمد",
      companyName: "مؤسسة الهيبة",
      phone: "01210987654",
      address: "شارع الحرية، الشروق",
      governorate: "القاهرة",
      city: "الشروق",
    },
    {
      fullName: "منير عبدالمنعم حسن",
      companyName: "شركة الجلال التجارية",
      phone: "01009876543",
      address: "شارع المحطة، بدر",
      governorate: "القاهرة",
      city: "بدر",
    },
    {
      fullName: "ناصر عبدالرؤوف علي",
      companyName: "مجموعة العظمة",
      phone: "01198765432",
      address: "شارع الجيش، العاشر من رمضان",
      governorate: "الشرقية",
      city: "العاشر من رمضان",
    },
    {
      fullName: "هاني عبدالغني محمود",
      companyName: "شركة السيادة",
      phone: "01287654321",
      address: "شارع الثورة، السادس من أكتوبر",
      governorate: "الجيزة",
      city: "السادس من أكتوبر",
    },
    {
      fullName: "وحيد عبدالباسط أحمد",
      companyName: "مؤسسة الهمة",
      phone: "01076543210",
      address: "شارع الجمهورية، أكتوبر الجديدة",
      governorate: "الجيزة",
      city: "أكتوبر الجديدة",
    },
    {
      fullName: "يحيى عبدالجواد محمد",
      companyName: "شركة العزيمة",
      phone: "01165432109",
      address: "شارع النصر، زايد الجديدة",
      governorate: "الجيزة",
      city: "زايد الجديدة",
    },
    {
      fullName: "زكريا عبدالحكيم حسن",
      companyName: "مجموعة الإرادة",
      phone: "01254321098",
      address: "شارع الحرية، القاهرة الجديدة",
      governorate: "القاهرة",
      city: "القاهرة الجديدة",
    },
    {
      fullName: "أنور عبدالرحيم علي",
      companyName: "شركة الطموح",
      phone: "01043210987",
      address: "شارع المحطة، الساحل الشمالي",
      governorate: "مطروح",
      city: "الساحل الشمالي",
    },
    {
      fullName: "بهاء عبدالكريم محمود",
      companyName: "مؤسسة التحدي",
      phone: "01132109876",
      address: "شارع الجيش، العلمين الجديدة",
      governorate: "مطروح",
      city: "العلمين الجديدة",
    },
  ];

  const merchants = merchantData.map((data, i) => ({
    userType: "merchant",
    fullName: data.fullName,
    email: `merchant${i + 1}@example.com`,
    password: hashedPassword,
    phone: data.phone,
    address: data.address,
    governorate: data.governorate,
    city: data.city,
    storeName: data.companyName,
    companyName: data.companyName,
  }));

  console.log(JSON.stringify(merchants, null, 2));
}

generateMerchants();
