const fs = require("fs");

const merchants = JSON.parse(fs.readFileSync("merchants.json", "utf8"));

// New unique merchant names (different from employees/couriers)
const merchantNames = [
  "صلاح الدين يوسف",
  "عبدالله فيصل",
  "حمزة عثمان",
  "زياد طلال",
  "فهد عبدالرحمن",
  "نواف سلطان",
  "راشد خالد",
  "سعود ماجد",
  "عمار حسام",
  "ثامر نايف",
  "غسان وليد",
  "جاسم عادل",
  "طلال رشيد",
  "عدنان كريم",
  "فراس محمود",
  "نبيل سامي",
  "وسام جمال",
  "عماد طارق",
  "رياض أحمد",
  "سليم حسن",
  "منذر علي",
  "قصي محمد",
  "لؤي إبراهيم",
  "مازن يوسف",
  "هيثم عمر",
  "بشار سعيد",
  "عامر فتحي",
  "نضال صلاح",
  "إياد رامي",
  "شادي باسم",
  "رائد معتز",
  "وائل تامر",
  "حاتم عصام",
  "سامر فادي",
  "عاصم نادر",
  "ماهر مروان",
  "صفوان جمال",
  "عزام سيد",
  "حازم منير",
  "كنان حمدي",
  "أسامة ماهر",
  "بلال ياسين",
  "جهاد زياد",
  "رشاد عادل",
  "سهيل إيهاب",
  "طاهر مدحت",
  "عبيدة فتحي",
  "فيصل سمير",
  "قيس نبيل",
  "ليث رفعت",
];

// Generate unique emails based on new names
const emailPrefixes = [
  "salah.youssef",
  "abdullah.faisal",
  "hamza.othman",
  "ziad.talal",
  "fahd.abdelrahman",
  "nawaf.sultan",
  "rashed.khaled",
  "saud.maged",
  "ammar.hossam",
  "thamer.nayef",
  "ghassan.walid",
  "jassem.adel",
  "talal.rasheed",
  "adnan.karim",
  "feras.mahmoud",
  "nabil.samy",
  "wessam.gamal",
  "emad.tarek",
  "riyad.ahmed",
  "salim.hassan",
  "munther.ali",
  "qusay.mohamed",
  "louay.ibrahim",
  "mazen.youssef",
  "haitham.omar",
  "bashar.said",
  "amer.fathy",
  "nidal.salah",
  "eyad.ramy",
  "shady.bassem",
  "raed.moataz",
  "wael.tamer",
  "hatem.essam",
  "samer.fady",
  "asem.nader",
  "maher.marwan",
  "safwan.gamal",
  "azzam.sayed",
  "hazem.mounir",
  "kinan.hamdy",
  "osama.maher",
  "bilal.yassin",
  "jehad.ziad",
  "rashad.adel",
  "sohail.ehab",
  "taher.medhat",
  "obaida.fathy",
  "faisal.samir",
  "qais.nabil",
  "layth.refaat",
];

const updatedMerchants = merchants.map((merchant, index) => ({
  ...merchant,
  fullName: merchantNames[index],
  email: `${emailPrefixes[index]}@gmail.com`,
}));

fs.writeFileSync(
  "merchants.json",
  JSON.stringify(updatedMerchants, null, 2),
  "utf8"
);
console.log("✅ Updated all merchant names and emails to be unique");
